[phases.setup]
nixPkgs = ["rustc", "cargo", "pkg-config"]

[phases.install]
cmds = ["cargo build --release"]

[phases.build]
cmds = ["cargo build --release"]

[start]
cmd = "./target/release/jambonne-site" 