# Example complex Railway setup with multiple services

[build]
builder = "nixpacks"

[deploy]
startCommand = "cargo run --release"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Example environment variables for database connection
[deploy.env]
DATABASE_URL = "postgresql://user:pass@host:5432/dbname"
REDIS_URL = "redis://host:6379"
API_KEY = "your-api-key"

# Example service dependencies
[deploy.dependencies]
database = "postgresql"
cache = "redis" 